# Generated by Django 4.2 on 2026-05-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'System Admin'), ('owner', 'Parlour Owner'), ('staff', 'Service Staff'), ('customer', 'Customer')], max_length=20)),
                ('module_name', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=50)),
                ('is_allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
