# Generated by Django 4.2 on 2026-05-16 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0002_rolepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parlour',
            old_name='created_at',
            new_name='date_registered',
        ),
        migrations.RemoveField(
            model_name='parlour',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='parlour',
            name='address',
            field=models.TextField(default='Ahmedabad, Gujarat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parlour',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parlour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parlour',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlours', to=settings.AUTH_USER_MODEL),
        ),
    ]
