# Generated by Django 4.2 on 2026-05-16 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0004_mastercategory_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global_commission_percentage', max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=10.0, help_text='Default commission percentage cut', max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='parlour',
            name='custom_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set above 0 to override global rate', max_digits=5),
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique Gateway Order/Payment ID', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='UPI / Card', max_length=50)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Success', max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('parlour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Admin.parlour')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_reference', models.CharField(help_text='Bank transfer UTR or Txn ID', max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('parlour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='Admin.parlour')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
