# Generated by Django 4.2 on 2026-05-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Official response text sent by platform admin', null=True),
        ),
    ]
