# Generated by Django 4.2 on 2026-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_supportticket_admin_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(help_text='e.g., FESTIVAL20, BEAUTYQ50', max_length=20, unique=True)),
                ('offer_name', models.CharField(help_text='e.g., Monsoon Flash Discount', max_length=100)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage (%)'), ('Flat', 'Flat Amount (₹)')], default='Percentage', max_length=15)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage rate or direct flat deduction cut', max_digits=6)),
                ('min_basket_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum appointment billing required to apply code', max_digits=8)),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility across platform checkout loops')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
