# Generated by Django 4.2 on 2026-05-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_globaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='field_type',
            field=models.CharField(default='text', help_text='text, textarea, or boolean', max_length=20),
        ),
        migrations.AddField(
            model_name='platformsetting',
            name='label',
            field=models.CharField(default='Platform Setting', help_text='Human-readable title, e.g., Support Contact Email', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='key',
            field=models.CharField(help_text='Unique internal code handle, e.g., platform_email', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='platformsetting',
            name='value',
            field=models.TextField(help_text='The actual running parameter value stored'),
        ),
    ]
