# Generated by Django 4.2 on 2026-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0003_promocode_servicepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(default='hair', max_length=100),
        ),
    ]
