# Generated by Django 4.2 on 2026-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0004_service_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('position', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
