# Generated by Django 4.2 on 2026-04-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0005_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('role', models.CharField(blank=True, help_text='e.g., Hair Stylist, Manicurist', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='parlour.staff')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('staff', 'date', 'start_time')},
            },
        ),
    ]
