# Generated by Django 4.2 on 2026-04-15 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parlour', '0006_dutyroster'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., March 2026 (Week 1)', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='beautician',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='beautician',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dutyroster',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('beautician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='parlour.beautician')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='parlour.payoutperiod')),
            ],
            options={
                'unique_together': {('beautician', 'period')},
            },
        ),
    ]
